title: Facts and Logic
logo:  # You can add own logo image.
description: “Thanks for visiting my blog”
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://changhaowu.github.io/" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Changhao Wu
  bio: Thanks for visiting my blog

# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
github: https://github.com/changhaowu/ # your github handle
instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
#email: forexample@website.com # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Karl Wu's Blog # Add your hero title
hero-subtitle: I know nothing except the fact of my ignorance # Add your hero subtitle
hero-image: images/cover/C_Scenery1.jpeg # Add background image in section hero

# Footer
footer-image: images/cover/A1.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier:  Karl Wu# Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-toc
  - jekyll-archives
  
jekyll-archives:
  enabled:
    -month
    -year
  layouts:
    tag: tag-archive
  layout: archive
  permalinks:
    #year: '/:year/'
    #month: '/:year/:month/'
    #day: '/:year/:month/:day/'
    #tag: '/tag/:name/'
    #category: '/category/:name/'
    
url: "https://changhaowu.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages



# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
  
